#!/bin/bash

# Where are the data files located?
dataDir=${DATA:-data}

# Provide fallback for sponge
if ! hash sponge &> /dev/null; then
	sponge () {
		tmpfile=`mktemp`
		cat > $tmpfile

		mv $tmpfile $1
	}
	export -f sponge
fi

find "$dataDir" -type f -not -path "*0/*" -not -name "tmp*" -print0 \
	| xargs -0 -I '{}' bash -c "sort -u {} | sponge {}"
